name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install_deps: sudo apt-get install libboost-all-dev
            build_command: g++ -std=c++11 main.cpp -o main -lboost_system
          - os: windows-latest
            install_deps: |
              git clone https://github.com/Microsoft/vcpkg.git
              cd vcpkg
              ./bootstrap-vcpkg.sh
              ./vcpkg integrate install
              ./vcpkg install boost
            build_command: cl /EHsc main.cpp /I"C:\vcpkg\installed\x64-windows\include" /link /LIBPATH:"C:\vcpkg\installed\x64-windows\lib"
          - os: macos-latest
            install_deps: brew install boost
            build_command: g++ -std=c++11 main.cpp -o main -lboost_system

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: ${{ matrix.install_deps }}

    - name: Setup MSVC
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: ${{ matrix.build_command }}